version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128m'
